'''
Write a program in Java and Python to check whether two numbers are amicable or not. Both the
number are generated by separate thread name of this thread is CSA and CSB. Amicable Number If
two numbers are such that the sum of the perfect divisors of one number is equal to the other number
and the sum of the perfect divisors of the other number is equal to the first number, then the numbers
are called Amicable Numbers.
The first few amicable pairs are: (220, 284), (1184, 1210),
(2620, 2924), (5020, 5564), (6232, 6368) 
'''

import threading
sum1,sum2 = 0,0

def amicable(num):
    sum = 0
    for i in range(1,num):  #starts from 0 if not mention 1
        if num%i == 0:
            sum += i
    return sum



def CS(lk,num):
    global sum1,sum2
    lk.acquire()
    sum = amicable(num)
    if sum1 == 0:
        sum1 = sum
    else:
        sum2 = sum
    lk.release()

lk = threading.Lock()
x,y = [int(z) for z in input().split()]
t1 = threading.Thread(target = CS, args = (lk,x))
t2 = threading.Thread(target = CS,args = (lk,y))
t1.start()
t2.start()
t1.join()
t2.join()
if sum1 == y and sum2 == x:
    print('amicable')
else:
    print('unamicable')
