/**
Write a program in Java and Python to check whether two numbers are amicable or not. Both the
number are generated by separate thread name of this thread is CSA and CSB. Amicable Number If
two numbers are such that the sum of the perfect divisors of one number is equal to the other number
and the sum of the perfect divisors of the other number is equal to the first number, then the numbers
are called Amicable Numbers.
The first few amicable pairs are: (220, 284), (1184, 1210), (2620, 2924), (5020, 5564), (6232, 6368) 
**/

import java.util.Scanner;

class Calculator extends Thread{
	int num = 0,sum = 0;
	public synchronized void run(){
		for(int i=1;i<num;i++){
			if(num%i == 0){
				sum += i;
			}
		}
	}
}

public class Amicable{
	public static void main(String[] args) {
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter two numbers");
		int x = sc.nextInt();
		int y = sc.nextInt();
		Calculator obj1 = new Calculator();
		Calculator obj2 = new Calculator();
		obj1.num = x;
		obj2.num = y;
		obj1.start();
		obj2.start();
		try{
			obj1.join();
			obj2.join();
		}
		catch(Exception ex2) {}
		if(obj1.sum == y &&  obj2.sum == x){
			System.out.println("Amicable");
		}
		else{
			System.out.println("Not amicable");
		}
	}
}